
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: auth_api_development

  username: postgres

  # The password associated with the postgres role (username).
  password: 
  host: localhost

  # The TCP port the server listens on. Defaults to 5432.
  # If your server runs on a different port number, change accordingly.
  port: 5432

test:
  <<: *default
  database: auth_api_test
  username: postgres
  password: 

production:
  <<: *default
  database: auth_api_production
  username: postgres
  password:
